# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hwayong Nam
#title: Ph.D candidate
email: hwayong.nam@scale.snu.ac.kr, nhy4916@gmail.com, nhy4916@snu.ac.kr
website: nam-hwayong.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Nam-hwayong
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hwayong-nam-682b18262
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Google scholar
  icon: <i class="fa-brands fa-google-scholar"></i>
  url: https://scholar.google.com/citations?user=-KkBvfUAAAAJ&hl=ko&oi=ao
#- title: another link
#  icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#  url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ID_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I am a Ph.D. candidate at Seoul National University (SNU), advised by Professor Jung Ho Ahn. Before joining SNU, I completed my BSE in Electrical and Electronics Engineering at Chung-Ang University (CAU).
  
  My main research area includes computer architecture, DRAM microarchitecture, memory system, and memory reliability and security. 
#  Recently, I have been focusing on memory system security, particularly related to the DRAM devices 
#  (e.g., read disturbance errors such as rowhammer/rowpress) and reverse-engineering the operations of commercial processors’ memory controllers. Also, I’m interested in enhancing system reliability against silient data corruptions (SDCs).

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>




content:
  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Seoul National University
  #       #link: 
  #       # link_text: boringcompany.com
  #       sub_title: Doctor of Philosophy
  #       caption: 2021 - present
  #       #quote: >
  #       #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Ph.D candidate in Department of Intelligence and Information
            
  #           Advisor: Jung Ho Ahn
  #     - layout: left
  #       title: Chung-Ang 
        
  #             University
  #       #link: 
  #       # link_text: boringcompany.com
  #       sub_title: Bachelor of Science
  #       caption: 2015 - 2021
  #       #quote: >
  #       #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           B.S.E in Electrical and Electronics Engineering
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ISCA
        #sub_title:
        caption: July 2024
        description: | 
            <b style="font-size: 1.2em;">DRAMScope: Uncovering DRAM Microarchitecture and Characteristics by Issuing Memory Commands</b>
            
            <b>Hwayong Nam</b>, Seungmin Baek, Minbok Wi, Michael Jaemin Kim, Jaehyun Park, Chihun Song, Nam Sung Kim, Jung Ho Ahn
      - layout: left
        title: ACM ICS
        #sub_title:
        caption: May 2024
        description: | 
            <b style="font-size: 1.2em;">CLAY: CXL-based Scalable NDP Architecture Accelerating Embedding Layers</b>
            
            Sungmin Yun, <b>Hwayong Nam</b>, Kwanhee Kyung, Jaehyun Park, Byeongho Kim, Yongsuk Kwon, Eojin Lee, Jung Ho Ahn



# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
